best-practices/tagging/index.html

Draft of tagging best practices. Added material from [eBraille Examples](https://github.com/daisy/ebraille/wiki/eBraille-Examples) and from other decisions made by the working group. Formatting looks right when viewed via Respec but probably needs to be further improved. There's still a lot that needs to be added such as additional examples and explanations. There are certainly more kinds of tagging and class names to add but this should be a good start for the working group to review and improve together.

Update index.html in Tagging Best Practices folder

---

best-practices/tagging/index.html
common/js/status.js
index.html

Because we're using the respec base profile to add DAISY's branding, we don't have access to use the built-in specification status identifiers (plus these are W3C-specific).
This pull request adds a new property called "daisyStatus" to the respec metadata to identify the status. For now, I've matched the respec pattern of it having the values "ED" for editor's draft and "WD" for working draft. (There are also "CR", "PR", and "REC" placeholder codes, but we can figure out if we need some or all of these for DAISY process later.)
When you add these codes, there's a post-processing script that will add the corresponding status designator to the header before the publication date.
The preview for the specification should provide an example of the functionality (assuming scripting works with …

Add document status to header

---

common/js/status.js
common/status.html
index.html

This pull request makes the following changes:
- it adds a definition of ebraille file set based on the ocf abstract container
- it adds a publication resources section;
- it adds a "status of this document" section - a sort of slimmed down version of what respec generates for w3c;
- it starts to fill in some of the basic requirements for the package document and adds some bare bones examples;
- it adds introductions to all the sections to start explaining the purpose of each
There's still a lot more to do, of course, but I don't want to grow this pull request too big. It should allow us to tackle the individual sections in more detail in later pull requests.

Updated spec requirements

---

index.html

After merging the last pull request, I noticed that I made some unintentionally strong connections to aspects of epub that we haven't settled on yet. In particular, this pull request:
- removes wording about an ebraille publication being a conforming epub publication, as that would mean an ebraille publication would have to be packaged (I thought we defined that requirement elsewhere from a publication in epub, but it's part of its definition)
- removes the requirements for the mimetype and container.xml files for now. We've only agreed on the file set, and these two files are technically a requirement of the packaging. We can add them later when we figure out if they always have to be present or if we can dynamically generate them as part of the packaging.
- makes some additional minor …

Adjust relationship to epub 3

---

best-practices/tagging/index.html

The changes in this commit address the following issues with the Tagging Best Practices document:
- Added Matt Garrish as editor.
- Added James Bowden as author.
- Fixes #159
- Fixes #155
- Fixes #154
- Fixes #58
- Fixes #47
- Fixes #30
- Fixes #28
- Fixes #9
- Fixes #4
- Fixes #3
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/160.html" title="Last updated on Apr 16, 2024, 6:09 PM UTC (321f493)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/160/b2addfd...321f493.html" title="Last updated on Apr 16, 2024, 6:09 PM UTC (321f493)">Diff</a>

Updated Tagging Best Practices

---

index.html

I was going to make a tweak to the abstract, but I noticed we don't have a proper overview for the document. I took the second paragraph from the abstract and added some more text to it to create one. Suggestions on how it can be improved are welcome.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/intro-edits/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/intro-edits/index.html)

Add overview

---

index.html

Here's a start on the new section. Let me know if this makes sense and if there are any improvements or additions that can be made to it.
* [Preview](https://raw.githack.com/daisy/ebraille/add/future-directions/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/add/future-directions/index.html)

Add future directions section

---

index.html

As discussed on the last editor's call, this pull request adds an informative section explaining how additional resources can be included in an ebraille publication without triggering epub's fallback requirements.
I've also added a definition for "ebraille creator".
* [Preview](https://raw.githack.com/daisy/ebraille/spec/extra-res/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/extra-res/index.html)

Add informative section about exempt resources

---

index.html

This pull request explicitly bans the fixed layout properties from being specified. I was going to blanket ban all of them, since the default layout is always reflowable, but there may be some good reason why someone wants to explicitly declare their publication is reflowable.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/no-fxl/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/no-fxl/index.html)

Add restriction on declaring fixed layout properties

---

index.html

I've moved the mention of the tagging best practices from a note in the introduction to content documents into its own section. I've also added a link to the future styling guide although I realize it won't actually work.
I also made a start at an accessibility section to push people to follow the epub accessibility specification, as much as it can apply to a braille document. (Making the metadata mandatory could be a later change.)
* [Preview](https://raw.githack.com/daisy/ebraille/spec/authoring/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/authoring/index.html)

Add best practices and accessibility sections

---

index.html

There's not a lot to say about media overlays beyond what epub already defines so I decided to give a brief recap of them as part of mentioning that they're supported. If people are okay with this approach, I might use it as a template for fleshing out some of the package document sections. Otherwise, we're kind of assuming everyone reading the specification will be fully familiar with the inner workings of epub.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/mo/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/mo/index.html)

Add media overlays section

---

index.html

Here's a first stab at reading system requirements. I went through the epub reading systems spec and listed out all the differences I could find in terms of support.
I'm less sure about the section on web-hosted publications, but leaving it in for now.
One question is do we want to mandate support for PDF for tactile images, should it be a recommendation, or do we need to mention it at all?
* [Preview](https://raw.githack.com/daisy/ebraille/spec/rs/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/rs/index.html)

Add ebraille reading system section

---

index.html

This pull request covers a few related topics:
- it sets the extension for packaged publications to .ebrl even though we haven't finalized the packaging details yet
- it adds an informative section on file extensions to the publication resources section to explain why we don't require specific ones for resources
- it adds a section on web deployment to cover setting the correct content-type headers and making sure the default document to serve is set
The ebrl extension can always be changed later if we decide on something else after we get the packaging sorted out.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/extensions-mediatypes/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/in …

File extensions and media types

---

index.html

Similar to the media overlays PR, I've expanded the sections on the package document manifest and spine to explain a bit more what they are for, what is required of them, and to give some examples. Additional links are provided to the fuller epub definitions.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/pkg-doc/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/pkg-doc/index.html)

Explain manifest and spine in more detail

---

index.html

This will only allow script elements if the primary entry page is not listed in the spine, so not reachable by users in a dedicated ebraille reading system.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/pep-scripting/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/pep-scripting/index.html)

Add exemption for scripting in primary entry page

---

index.html

This slims down the epub section to just what is relevant to ebraille given the restrictions we have on scripting, network access, and remote resources.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/security-privacy/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/security-privacy/index.html)

Add security and privacy section

---

index.html

This is just a starter section to link us up with EPUB's requirements. I expect there will be additions to it later.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/css/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/css/index.html)

Add section on css support

---

index.html

This pull request makes the following changes:
- it adds a couple of paragraphs to the end of the relationship to epub 3 section to explain how that also exposes us to the evolving standards that epub references (the html "living standard", unversioned svg, etc.).
- it adds an authoring shorthands section to explain that we sometimes use epub:type and dc: elements without showing their namespace declarations. I noticed we were guilty of this for epub:type already and will probably do the same once we flesh out the metadata
Otherwise, I've just rearranged the introduction a bit as it was getting a bit incoherent. The first three sections are now the descriptive ones - the overview, relationship to epub 3, and future directions - followed by the technical ones - terminology, conformance, …

Updates to intro sections

---

best-practices/styling/index.html
best-practices/tagging/index.html
common/js/status.js

This adds the status of this document section to both best practice guides. You can change these from the generic statement to something more specific if you want; you just have to delete the import div and write in a local statement.
It also adds a code for draft working group notes and the missing WG name to the respec metadata to make the top matter come out properly.
That should clear the lingering respec errors in the documents.
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/188.html" title="Last updated on Jun 13, 2024, 7:17 PM UTC (057d887)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/188/c8bda06...057d887.html" title="Last updated on Jun 13, 2024, 7:17 PM UTC (057d887)">Diff</a>

Add additional daisy top matter

---

index.html

This pull request recommends using only characters in the unicode braille patterns set as well as html whitespace for renderable text (as best as I could define that). I don't know that we want to make it a stronger restriction as there may be some cases where non-braille characters are needed. I mentioned mathml in the note, as I expect that would be one case (but let me know if I'm wrong).
It also clarifies that this recommendation only applies to the default rendition if adding multiple renditions.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/html-char/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https:/ …

Add text restriction on xhtml character data

---

index.html

This pull request expands the packaging section to require ebraille publications be zipped in an ocf zip container when distributed. I also recommend against using the font obfuscation algorithm to embed fonts since we're recommending in the css section that epub creators not set font properties. (We could make this a must not, but then it seems like there should be a stronger ban on font-family changes.)
In trying to add the reading system requirements, I noticed that the reading system section was getting a bit big and hard to read. To try and make it more readable, I've made the following changes:
- there's now a general requirements section that covers how we diverge from epub
- there's a new unsupported features section that covers the features we're telling epub creators not to use …

Packaging and reading system requirements

---

index.html

This pull request moves the metadata requirements into the main specification.
I'm opening this pull request a bit early to start getting feedback. I've tried to fill in some of the sections as best I can with some more details from how epub defines/handles them, but I may have some things wrong (especially whether some properties can be repeated). We also discussed some additional changes in the last meeting that I haven't tried to go back and integrate yet. Let me know whatever you spot that needs fixing or needs more detail.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/metadata/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3 …

Integrate metadata guide

---

index.html

Changes the name to sourcePublisher to avoid assumptions about the source format and better align with the dtb property.
Also adds an entry to the vocabulary as we were missing one for printPublisher.
Fixes #201 
* [Preview](https://raw.githack.com/daisy/ebraille/metadata/rename-printpublisher/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/metadata/rename-printpublisher/index.html)

Rename printPublisher property

---

index.html

I noticed that our abstract wasn't really saying anything specific about the format, as I expect it was a placeholder from when we created the document. This adds another paragraph to it so it now reads:
> This specification defines eBraille, a digital reading format for braille publications.
> 
> The eBraille file set is based on Open Web Technologies, such as XHTML and CSS, and provides the ability to encode braille in semantically enhanced markup, allowing it to adapt to the different capabilities of braille reading devices. The file set is designed for both packaged distribution to end users and deployment to the web for online and downloadable reading.
Let me know if there's anything else we should highlight in the abstract, or that doesn't need saying in the above.
* …

Updated abstract

---

index.html

One last ambiguity I noticed is that packaging isn't required so it's not clear if the mimetype and container.xml files are required all the time or not.
This PR makes them optional when the file set is not packaged, since their only purposes are for identifying the container and locating the package document within it. If you don't package the file set, the required naming and location of the entry page and package document already take care of discovery, plus there's the required link to the package document in the entry page.
It probably makes life easier to have them around so it's easier to zip up the file set, and authoring tools may well always spit them out, but I don't think we need to require them if a publisher has no interest in packaging their publications.
Differences of …

Clarify packaging files are optional when not packaging

---

best-practices/styling/index.html

This is some cleanup of the Styling Best Practices. I've removed most of the editor's notes and added some more links to Github issues.

Styling Best Practices: remove some editor's notes

---

best-practices/styling/index.html
best-practices/tagging/index.html
common/js/copyright.js
index.html

This adds a small script to handle copyright year ranges. Only the copyright start year needs to be in the span in the body. If it doesn't match the current year, the script converts it to a range from the start year to the current year.
Fixes #233
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/240.html" title="Last updated on Aug 7, 2024, 2:47 PM UTC (de1bfa8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/240/9106650...de1bfa8.html" title="Last updated on Aug 7, 2024, 2:47 PM UTC (de1bfa8)">Diff</a>

Auto-generate the copyright year

---

best-practices/tagging/index.html

Removed "various strings" from box reserved class values.
Replaced br with wbr in multiline heading example. Also added a note explaining the preference for wbr over br.
Closed a p tag. Added a comma and space where it was previously missing in the paragraph reserved class values.
Fixes #227
Fixes #224
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/253.html" title="Last updated on Aug 29, 2024, 12:53 PM UTC (d4232c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/253/aa004f1...d4232c1.html" title="Last updated on Aug 29, 2024, 12:53 PM UTC (d4232c1)">Diff</a>

Remove "various strings," adds wbr and &shy; examples, and minor cleanup

---

best-practices/tagging/index.html

Changes "Reserved class values" to "Supported role values" under page numbers. Was not sure if "role" still needed to be treated as code same as "class" but thinking it does.
fixes #230
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/254.html" title="Last updated on Aug 27, 2024, 5:46 PM UTC (a590773)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/254/447482f...a590773.html" title="Last updated on Aug 27, 2024, 5:46 PM UTC (a590773)">Diff</a>

Replaced reserved class with supported role

---

index.html

This pull request adapts the OCF media type registration from epub 3.3 for ebraille. It defines application/ebrl+zip for ebraille files.
I removed the magic number part for the epub media type because it doesn't seem useful to check that for ebraille and we also are looser about accepting it so it may not even be where it should be. Otherwise, I've just adapted the text to call this the "ebraille implementation of the EPUB OCF zip container".
Let me know if there's anything that you think needs adjusting in this.
* [Preview](https://raw.githack.com/daisy/ebraille/spec/media-type/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec% …

Add media type registration

---

best-practices/styling/index.html
best-practices/tagging/index.html
common/js/examples.js
index.html

It doesn't look like we'll get a quick response from the respec group, so this will patch the example headings to add the needed aria attributes. When it's good to go, I can add it to the best practice guides before merging.
Fixes #256 
* [Preview](https://raw.githack.com/daisy/ebraille/spec/examples/index.html)
(Edit: removed the diff link as the changes are all in the attributes.)
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/266.html" title="Last updated on Sep 19, 2024, 5:37 PM UTC (0cae2f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/266/1574d98...0cae2f1.html" title="Last updated on Sep 19, 2024, 5:37 PM UTC (0cae2f1)">Diff</a>

Add heading role and level to examples

---

index.html

I've basically lifted the epub requirements for the element, but let me know if the date format should be further restricted.
Fixes #263 
* [Preview](https://raw.githack.com/daisy/ebraille/spec/issue-263/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/issue-263/index.html)

Add dc:date to required metadata

---

index.html

This is just a minor change to put the editor's note first until we get to figuring out the values for the element.

Move braille code future work note to start of section

---

best-practices/tagging/index.html

Leaving the example as blocked after changing the terminology to left-aligned was my mistake. Glad Bert caught it.
fixes #225
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/271.html" title="Last updated on Sep 23, 2024, 6:21 PM UTC (543f7c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/271/d1fc444...543f7c3.html" title="Last updated on Sep 23, 2024, 6:21 PM UTC (543f7c3)">Diff</a>

Replaced blocked with left-aligned in example

---

best-practices/tagging/index.html

Removes references to specify-number from both lists and paragraphs in Tagging Best Practices. In #226 it was agreed that these class values weren't really "best practices" and more a loophole that could be utilized to make less than ideal eBraille files. If someone wants to do it, fine, but we probably shouldn't recommend it.
Fixes a typo in "poetry" description by adding the word "be."
fixes #226
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/270.html" title="Last updated on Sep 23, 2024, 5:00 PM UTC (a8d591a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/270/d1fc444...a8d591a.html" title="Last updated on Sep 23, 2024, 5:00 PM UTC (a8d591a)">Diff</a>

Remove references to specify-number

---

best-practices/tagging/index.html

Nest `ol` inside `li` and removed superfluous `ol class="exercise"`
fixes #210
***
<a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/pull/272.html" title="Last updated on Sep 26, 2024, 1:20 PM UTC (c1b76a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/daisy/ebraille/272/d1fc444...c1b76a8.html" title="Last updated on Sep 26, 2024, 1:20 PM UTC (c1b76a8)">Diff</a>

Exercise example has correct markup

---

best-practices/styling/index.html

see https://github.com/daisy/ebraille/issues/94 and https://github.com/daisy/ebraille/issues/231.
[Preview](https://raw.githack.com/daisy/ebraille/whitespace-handling/best-practices/styling/index.html?developer-mode=true#white-space)

CSS best practices: use BANA number line example as example for white space handling

---

index.html

This pull request adds the property for expressing the date on which the source was published.
Should we also move this and sourcePublisher to the recommended properties list, as I asked in #221? Looking at the sourcePublisher definition, it says to add "N/A" if there isn't a source publisher, which is a strong case for not making it required.
Required metadata should always have a meaningful value, otherwise we keep having to propagate a workaround. It's never great to require language-specific values like "N/A", which I'll have to work into the date if we keep them required.
Fixes #221 
Fixes #200 
Fixes #168 
* [Preview](https://raw.githack.com/daisy/ebraille/spec/issue-200/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url …

Add sourceDate property

---

index.html

This pull request adds a recommendation to the xhtml character encoding section not to use CSS that would add non-braille characters to the text.
It also adds a section on formatting xhtml ordered and unordered lists with a recommendation to embed the list numbering rather than rely on the default styling.
There's also a minor fix to a broken link and I changed the word "required" to "expected" at the start of the section on character encoding so it doesn't sound contradictory to the actual normative recommendation we have about the use of braille characters.
Related to #273

Add recommendations against using css that adds non-braille characters

---

index.html

Fixes #194 
***
[Preview](https://raw.githack.com/daisy/ebraille/spec/celltype/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/celltype/index.html)

Rename cellType to brailleCellType

---

index.html

It just occurred to me that we're using versioned EPUB references to the 3.3 release. That was fine when we started because EPUB 3.3 was supposed to be an "evergreen" specification - updatable without changing version numbers. But that didn't last long because we were limited to not introducing any new features, so we've just rechartered and are starting a 3.4 revision.
Long story short, our references to 3.3 will capture a point in time release of EPUB 3, sending people to outdated information once 3.4 and any future releases come along.
To avoid this, I've changed all the EPUB specification references to be unversioned. For example, instead of references to "epub-33" the new reference to "epub3" uses a link that resolves to whatever the latest version is. It also required changing all …

Use undated refs for epub3 specs

---

index.html

This pull request addresses the feedback received on list from @jylioja21
Most notably:
- it removes the `dateTranscribed` property
- it rewords the note about how an ebraille file with a .epub extension would be handled. This is tricky to say definitively as the media type could be the determining factor if the file is served over the web, for example. And unless the user is already in a reading system, it might be the operating system that routes the file to the wrong type of reading agent based on its extension.
***
[Preview](https://raw.githack.com/daisy/ebraille/spec/typos/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%2 …

Various fixes from feedback

---

index.html

This pull request adds the following clarifications and changes:
- it moves the requirement that all files be below the root directory into the section on files and directories
- it moves the restriction on referencing remote resources into the section on using urls in the fileset
- it adds a note that setting xml:lang in the package document only defines the language of the metadata in that file
- it expands the text for the package element example to refer readers for more information on unique identifiers to the dc:identifier section and to explain that xml:lang attribute sets the package text to English.
- it expands on the note for dc:date to explain that this is not the date of the source work and refers readers to the dc:source section for setting for more info.
- it clarifies in …

Fixes for additional feedback

---

index.html

This pull request moves the vocabulary definition lists back to their definitions in package metadata section and devolves appendix A from duplicating the EPUB vocabulary setup to being more of an extension definition. Only the optional metadata field definitions remain in the appendix. It also adds definitions for the dublin core elements and properties to make the definitions in the body more like the EPUB specification.
On a secondary note, I've rearranged the metadata sections to use descriptive names instead of sorting by prefixed element and property names.
Fixes #311 
* * *
[Preview](https://raw.githack.com/daisy/ebraille/spec/meta-retool/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraill …

Move meta tag definition fields to body

---

index.html

This pull request incorporates the change described in issue #312. It removes graphicType and requires tactileGraphics to either have the value "none" or the comma-separated list of formats that used to be in graphicType.
Fixes #312 
* * *
[Preview](https://raw.githack.com/daisy/ebraille/spec/merge-graphics-meta/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/merge-graphics-meta/index.html)

Remove graphicType and merge its functionality with tactileGraphics

---

index.html

(Sorry, I realized I named the branch after the wrong issue, so reopening this under the corrected name. Nothing changed from #323.)
Per the comments in #317, this pull request moves the restriction on manifest fallbacks to the resource fallbacks section and changes the "unsupported features" section to "additional unsupported features".
Fixes #317 
* * *
[Preview](https://raw.githack.com/daisy/ebraille/spec/issue-317/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/issue-317/index.html)

Move the restriction on manifest fallbacks

---

index.html

I've gone through the metadata properties and reworded all the text that was describing requirements already in EPUB 3 so that they aren't normatively re-requiring the same things.
Fixes #319 
* * *
[Preview](https://raw.githack.com/daisy/ebraille/spec/issue-319/index.html) | [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/issue-319/index.html)

Reword repeated metadata requirements from EPUB 3

---

index.html

This PR attempts to address #316 by making the following changes:
- **publication conformance:**
- add a conformance statement saying eBraille MUST conform to EPUB except for documented willful violations
- change the way we refer to packaging requirements (see below)
- **eBraille file set:**
- make eBraille file set a virtual file set that MUST conform to OCF abstract container
- define two materializations of the eBraille file set in two new subsections, **Packaged eBraille file set** and **Unpackaged eBraille file set**.
- move the publication resources location conformance statement to the “Publication resources” section. The “URLs in the file set” section becomes informative (it inherits from the EPUB one).
- **deployment:**
- replace the “Web deployment” section by a more generic …

clarify the relationship to EPUB
